### ISSUE TITLE
When using certain resource packs, not all entity textures change on the radar.

### ISSUE THREAD

**Issue by razorchase49** [fantahund/VoxelMap#21]
When switching from Default/Programmer textures to a resource pack like PureBDcraft, or vice versa, some of the entities on the radar maintain the same texture they had prior to switching packs. Which mobs correctly change textures and which ones don't are random and there seems to be no pattern. For example, here are screenshots showing the radar in the top-right corner before an after switching resource packs:
Here is a screenshot of the Programmer Art entity textures on the minimap radar before switching:
![2023-06-18_09 25 44](https://github.com/Updated-VoxelMap/VoxelMap/assets/19761194/b8628c5b-c9c0-448d-bf50-be554b4a1b4d)
Here is a screenshot with PureBDcraft enabled, and on the radar, you can see that some mob textures changed, but ones such as the Enderman, Witch, and Drowned have not changed (remain as Programmer Art textures):
![2023-06-18_09 26 11](https://github.com/Updated-VoxelMap/VoxelMap/assets/19761194/3b6dec4a-e0db-4bc5-b8de-dffe4e81655c)
Oddly enough, this only occurs when using PureBDcraft, for me anyway. I've used other resource packs such as John Smith Legacy, Excalibur, Dokucraft, Ozocraft, etc. and switching to and from those packs do not replicate this bug. So I'm not too sure what it is about BDcraft. Maybe the 128x resolution? But I doubt it.
If this helps, and I actually don't know if it's relevant, but I did recieve this error message when changing between the packs:

> [09:25:34] [Voxelmap LiveMap Calculation Thread/ERROR]: Voxelmap LiveMap Calculation Thread
java.lang.IllegalArgumentException: (806, 436) outside of image bounds (512, 512)
	at net.minecraft.class_1011.method_4305(class_1011.java:206) ~[client-intermediary.jar:?]
	at com.mamiyaotaru.voxelmap.util.ScaledMutableNativeImageBackedTexture.setRGB(ScaledMutableNativeImageBackedTexture.java:49) ~[voxelmap-1.20.1-1.12.8.jar:?]
	at com.mamiyaotaru.voxelmap.Map.mapCalc(Map.java:869) ~[voxelmap-1.20.1-1.12.8.jar:?]
	at com.mamiyaotaru.voxelmap.Map.run(Map.java:250) ~[voxelmap-1.20.1-1.12.8.jar:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]

This occurs for Voxelmap 1.20.1-1.12.8, as well as 1.19 versions.

**Comment by fantahund** [comment]
Fixed in 1.21.4 Version, will be published in the next few days.
