### ISSUE TITLE
Lighting on map does not work when y < 0

### ISSUE THREAD

**Issue by razorchase49** [fantahund/VoxelMap#22]
Issue:
When placing light-emitting blocks like lava, torches, etc. in an area below y = 0, the surrounding area does not light up on the minimap or fullscreen map. I have two screenshots demonstrating:
Here is a screenshot of a lava pool on the minimap at y = 29, where the lighting around the lava works fine.
![2023-06-17_17 32 12](https://github.com/Updated-VoxelMap/VoxelMap/assets/19761194/1ff772c2-4909-45d5-8c09-fed73d38988b)
Here is a screenshot of a lava pool on the minimap at y = -33, where although the lava itself glows on the minimap, the area around it is not lit up at all.
![2023-06-17_17 32 39](https://github.com/Updated-VoxelMap/VoxelMap/assets/19761194/04a032c8-3664-4104-b45a-c15d56aceba0)
I don't have a screenshot proving it, but when exploring a mineshaft below y = 0, lit with torches, the lighting does not show at all on the minimap.
This happens in Voxelmap version 1.20.1-1.12.8.

**Comment by Brokkonaut** [comment]
Fixed in 33949c7eda6397d4afadda14caa127d9618d752c
