### ISSUE TITLE
OpenGL debug message spammed in logs

### ISSUE THREAD

**Issue by paradoxx42** [fantahund/VoxelMap#25]
When adding VoxelMap to my mods list, the following message is spammed 60 times per second in the log (console by PrismLauncher):

[22:13:24] [Render thread/INFO]: OpenGL debug message: id=1000, source=API, type=ERROR, severity=HIGH, message='No detailed debug message due to a non-debug context'

The message only appears when loaded into a world or server, after leaving, the render thread is stopped:

[22:13:24] [Render thread/INFO]: Stopping worker threads

My list of mods is the following:

  [✔] carpet-extra-1.19.4-1.4.100
  [✔] carpet-fixes-1.19.4-1.14.1
  [✔] carpet-tis-addition-mc1.19.4-v1.58.0
  [✔] chunk-debug-1.19.4-1.0.8
  [✔] clientcommands-2.7.13
  [✔] CraftPresence-2.3.9+1.19.4
  [✔] elytratrims-fabric-3.1.1+1.19.4
  [✔] enhancedblockentities-0.9+1.19.4
  [✔] essentialaddons-1.19.4-1.2.2
  [✔] essential-client-1.19.4-1.4.2
  [✔] fabric-api-0.87.2+1.19.4
  [✔] fabric-carpet-1.19.4-1.4.101+v230319
  [✔] fabric-language-kotlin-1.10.19+kotlin.1.9.23
  [✔] farsight-fabric-1.19.4-3.5
  [✔] invhud.fabric.1.19.4-3.4.18
  [✔] iris-mc1.19.4-1.6.11
  [✔] isometric-renders-0.4.4+1.19.4
  [✔] itemscroller-fabric-1.19.4-craftfix-1.2.7
  [✔] litematica-fabric-1.19.4-0.14.3
  [✔] litematica-server-paster-mc1.19.4-v1.2.0
  [✔] litemoretica-1.2.5+mc1.19.4
  [✔] lithium-fabric-mc1.19.4-0.11.1
  [✔] malilib-fabric-1.19.4-0.15.4
  [✔] masaadditions-1.2.0+1.19.4
  [✔] minihud-fabric-1.19.4-0.26.2
  [✔] minimapsync-1.1.2+mc1.19.4
  [✔] modmenu-6.3.1
  [✔] owo-lib-0.10.6+1.19.4
  [✔] pistorder-mc1.19.4-v1.6.4
  [✔] sodium-fabric-mc1.19.4-0.4.10+build.24
  [✔] syncmatica-1.18.2-0.3.10
  [✔] techutils-0.3.0-beta.4+1.19.4
  [✔] tweakermore-mc1.19.4-v3.17.0
  [✔] tweakfork-fabric-1.19.4-1.2.3
  [✔] voxelmap-1.19.4-1.12.8
  [✔] worldedit-mod-7.2.14

**Comment by fantahund** [comment]
The bug is not that bad for now, it has been around forever. i also believe that it has been fixed since 1.20.4. We only give support for current versions anyway ^^
