### ISSUE TITLE
Lighting on map is weird when y > 256

### ISSUE THREAD

**Issue by dolmondboi** [fantahund/VoxelMap#26]
I was working on a brick pyramid that goes to build height and I noticed that the lighting gets really dark at any y level over 256. I imagine this is probably due to the world height change, but that is just a hunch. It happens in the mini map and the world map.
![weird_voxelmap_bug](https://github.com/fantahund/VoxelMap/assets/167498726/b317b618-53fa-4dba-bd83-1ebc4f8731b5)

**Comment by Brokkonaut** [comment]
Can you please try the latest dev build for 1.21 and see if it is fixed there?

**Comment by dolmondboi** [comment]
Do you mean the latest build that is on Modrinth? If so, I downloaded that and installed it, but I am having the same issue.
![1 21_VoxelMap_Problem_Minimap](https://github.com/fantahund/VoxelMap/assets/167498726/4756f770-8b39-4a37-a10b-ebafd427f6c8)
![1 21_VoxelMap_Problem_World_Map](https://github.com/fantahund/VoxelMap/assets/167498726/008fc5d9-54dd-4b50-a4b3-39c292a7d033)

**Comment by dolmondboi** [comment]
I also disabled all of my other mods that I originally had and only used Voxelmap and Fabric API and this problem was still happening, so I don't think it is a mod conflict.

**Comment by fantahund** [comment]
No, not the version from github. Try the version: https://jenkins.fantacs.de/job/VoxelMap/

**Comment by dolmondboi** [comment]
Ah, okay. Thank you. It does appear to be fixed in the latest build.
![1 21_VoxelMap_Problem_World_Map_Fixed](https://github.com/fantahund/VoxelMap/assets/167498726/4d22720d-0012-4a2f-8a51-1ef68cd1a670)
The minimap is working properly as well.
