### ISSUE TITLE
Many blocks in y=-2 are displayed in black color in both minimap and worldmap

### ISSUE THREAD

**Issue by ZnianXgang** [fantahund/VoxelMap#27]
Before I place Deepslate, the minimap displays the block color in y=-3 correctly.
![2024-05-30_21 15 41](https://github.com/fantahund/VoxelMap/assets/139073929/ceb3ac6c-a5bf-4e45-ab11-372907eadf9d)

When I placed Deepslate in y=-2, the minimap displays black color instead of the correct color.
![2024-05-30_21 15 53](https://github.com/fantahund/VoxelMap/assets/139073929/e984dac8-8037-4f11-87f2-badb12343176)

In worldmap. Those blocks in black are all in y=-2.
![2024-05-30_21 16 02](https://github.com/fantahund/VoxelMap/assets/139073929/114dd966-f7a9-4a2e-b791-b2655dae06dd)
![2024-05-30_21 35 24](https://github.com/fantahund/VoxelMap/assets/139073929/45adb36e-ac7f-4002-9d39-dd8fac3ff7a5)

This also affects many other blocks, even **water**.

Minecraft version: 1.20.4
Mod version: 1.12.17

**Comment by Brokkonaut** [comment]
Can you please try the latest dev build for 1.21 and see if it is fixed there?

**Comment by ZnianXgang** [comment]
> Can you please try the latest dev build for 1.21 and see if it is fixed there?

Fixed, thanks!
