### ISSUE TITLE
Hotbar and crosshair is missing on 1.21 with VoxelMap

### ISSUE THREAD

**Issue by Cpt-P** [fantahund/VoxelMap#28]
https://media.discordapp.net/attachments/809433062478708766/1251529991640977428/image.png?ex=666ee9a2&is=666d9822&hm=4bae77d1813df2e2d80c16a215d0d661b6918c7e6edd723ed81c4e06e5f1a56c&=&format=webp&quality=lossless&width=1173&height=606

**Comment by fantahund** [comment]
I need more information. It would be best if you sent me your last log so that I can take a look at it. ^^
