### ISSUE TITLE
Locale text is not loaded for multiworld

### ISSUE THREAD

**Issue by james-pre** [fantahund/VoxelMap#39]
The picture says it all:
![image](https://github.com/fantahund/VoxelMap/assets/75621402/45944fc7-ed9f-425f-8f51-ad7340f718a7)

**Comment by fantahund** [comment]
Fixed in latest devbuild [https://jenkins.fantacs.de/job/VoxelMap/](https://jenkins.fantacs.de/job/VoxelMap/)
I will publish it on Modrinth in the next few days, but you can already use the version from my jenkins.
