### ISSUE TITLE
Wrong mouse detection

### ISSUE THREAD

**Issue by MicrosoftPro12** [fantahund/VoxelMap#41]
If you tries to do a right click teleport on the map, you will be teleported to a wrong position due to the wrong cursor detection that the map thinks you are pointing another position instead of the real position you want.

It is likely due to the Mac's Retina display that resizes components on screen to get clearer views but will broke some hard-coded size detection.

Sorry for my poor English :(

I'm using:
MacBook Pro 13-inch, 2020 (Intel-based)
macOS Ventura 13.6.6
Minecraft Launcher b.2.26.2-1.10.2
VoxelMap 1.21 1.1.3.1 (older versions also apply)
Minecraft 1.21 with Fabric Loader 0.15.11 with Fabric API 0.100.4

Here's what it exactly is:

1.My original position is (1962, -588)
![2024-07-04_19 25 42](https://github.com/fantahund/VoxelMap/assets/95552468/7dd5b1fd-c468-400c-8a6a-fff4434b51e7)

2.When I held my cursor on my player icon, it says the cursor is pointing at (1881, -635)
<img width="848" alt="截屏2024-07-04 19 26 12" src="https://github.com/fantahund/VoxelMap/assets/95552468/3fa760a6-5df2-48b1-bfdc-5a70467149a2">

3.When I right click on my player icon and did a teleport, I didn't stay at the original position and teleported to (1881, -635)
<img width="844" alt="截屏2024-07-04 19 26 47" src="https://github.com/fantahund/VoxelMap/assets/95552468/e281bcab-549d-4b62-8311-1b94b486908d">

BTW here is another bug as gift: Error waypoint rendering:
![2024-07-04_19 27 07](https://github.com/fantahund/VoxelMap/assets/95552468/2cc4f055-e526-4865-9a63-c26578152752)

**Comment by hotsu0p** [comment]
It still works for me . It just depends on where you aim.

**Comment by fantahund** [comment]
Duplicated https://github.com/fantahund/VoxelMap/issues/30
