### ISSUE TITLE
If mobs/players wearing blocks on their head, block icon images still generate in game folder

### ISSUE THREAD

**Issue by ZnianXgang** [fantahund/VoxelMap#42]
### The Problem
Related to #14, images should not generate in game folder. However, when mobs/players wearing blocks on their heads, block icon images still generate.
### How to reproduce
Here I will use Carpet mod's `/player` command and [GCA](https://modrinth.com/mod/gca) mod's openFakePlayerInventory feature.

1. Create a new world in creative and open "Allow Commands" option, make sure Voxelmap's "Radar" and "Show Players" options are open;
2. Input `/carpet openFakePlayerInventory` and `/player hsds spawn` commands, the first one lets you have the ability to open fake players' inventory, the second one spawns a fake player named hsds.
3. Right-click hsds and place some blocks near Structure Void named **Stop all action**, then hsds should wear the blocks on his head and the minimap should display block items correctly;
4. See the game folder, the block icons still generate.

### Versions
Game version: 1.21
Mod version: 1.13.1 (Latest build: <https://github.com/fantahund/VoxelMap/actions/runs/9729509934>)

**Comment by fantahund** [comment]
fixed in https://github.com/fantahund/VoxelMap/commit/1f4cbeb08e69743123c1fd1abfbe11d08abe4487 Update coming with 1.21.4
