### ISSUE TITLE
VulkanMod compatibility?

### ISSUE THREAD

**Issue by UltraBlackLinux** [fantahund/VoxelMap#45]
Hey there,
sadly, VulkanMod is incompatible with VoxelMap. I find that quite unfortunate because that means that there's currently no minimap mod that does support vulkanmod, and the performance gain with vulkan is actually stunning.
Could you try to work out vulkanmod support here?
Thanks!
```
FATAL ERROR in native method: Thread[#1,Render thread,10,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.nglTexSubImage2D(Native Method)
	at org.lwjgl.opengl.GL11C.glTexSubImage2D(GL11C.java:2145)
	at com.mamiyaotaru.voxelmap.textures.TextureUtilLegacy.uploadTextureSub(TextureUtilLegacy.java:75)
	at com.mamiyaotaru.voxelmap.textures.TextureUtilLegacy.uploadTexture(TextureUtilLegacy.java:46)
	at com.mamiyaotaru.voxelmap.textures.TextureAtlas.stitch(TextureAtlas.java:88)
	at com.mamiyaotaru.voxelmap.textures.TextureAtlas.loadTextureAtlas(TextureAtlas.java:73)
	at com.mamiyaotaru.voxelmap.WaypointManager.onResourceManagerReload(WaypointManager.java:118)
	at com.mamiyaotaru.voxelmap.VoxelMap.apply(VoxelMap.java:105)
	at com.mamiyaotaru.voxelmap.VoxelMap.lateInit(VoxelMap.java:96)
```

**Comment by Brokkonaut** [comment]
While this would be a great feature, it is a huge amount of work. All render code would have to be rewritten, so this is rather unlikely in the near future.

**Comment by TheAlgorithm476** [comment]
About half a year ago, I have been in talks with the VulkanMod developers about compatiblity. We discussed it for a while, and attempted to come to a few solutions, but concluded that at this point, it would be too much of a change to feasibly pull off.

**Comment by UltraBlackLinux** [comment]
oh well, unfortunate.

Thanks for trying anyway.

**Comment by Felix14-v2** [comment]
Iirc JourneyMap added VulkanMod support some time ago

**Comment by TheAlgorithm476** [comment]
@Felix14-v2 while this is a valid fix, please refrain from promoting other mapping mods. Thanks

**Comment by Felix14-v2** [comment]
If I wanted to promote it, I would write comments about this specific alternative (which I've never used as I dislike closed source mods, I'm just following the VulkanMod development) regardless of an issue topic. This is a relevant info that may help other people, especially since the developers is not interested in work on VulkanMod compatibility. Thanks for understanding.

**Comment by UltraBlackLinux** [comment]
> @Felix14-v2 while this is a valid fix, please refrain from promoting other mapping mods. Thanks

I totally understand where you're coming from but I don't think you should censor the alternatives.
Every map mod has its features that make it stand out, if there's nothing that stands out then the mod is probably not relevant.

Journeymap has been around for a long time and is a great world map and minimap mod.
Xaero's stuff is also quite nice and modular with its own little ecosystem of compatible mods.
Voxelmap is also a very capable mod, but with the singular difference being that it's open source, which I think is a great feature that none of the other mods have to offer. 

I don't think it's justified to be scared of the alternatives. Players will find the mod that suits them the best on their own. And it's not like there are a ton of options. Every mod has its niche ;)

Just keep up the good work!
