### ISSUE TITLE
Mob helmet rendered as purple square in 1.21.3

### ISSUE THREAD

**Issue by LucaniaMC** [fantahund/VoxelMap#50]
![map1](https://github.com/user-attachments/assets/c547bc50-cc21-49a8-9648-28e8878af933)

In version 1.21.3, mobs with helmets appear to be a purple square.

There's also another issue in the same screenshot where sometimes the mob heads are rotated on the minimap.

**Comment by LucaniaMC** [comment]
Should I open another issue for the rotated mob heads?

**Comment by fantahund** [comment]
No, everything is fine with the turned mob heads, I already have that on the list. The radar broke completely with the version. so I had to do a lot of repairs. i'll have a look at it.

**Comment by LucaniaMC** [comment]
Thank you!!

**Comment by fantahund** [comment]
Head rotations fixed in https://github.com/fantahund/VoxelMap/commit/590b041b70106e6dcf09cdafd948832c642ba197 The fix comes with the 1.21.4 release

**Comment by fantahund** [comment]
Helm  textures fixed in https://github.com/fantahund/VoxelMap/commit/18c224ab0e1e06e17ce5ebd4f18957fceec80a09 The fix comes with the 1.21.4 release
