### ISSUE TITLE
Waypoint menu, toggle waypoint icon not showing in 1.21.3

### ISSUE THREAD

**Issue by Bluecubicgirl1** [fantahund/VoxelMap#52]
The icon that shows if a waypoint is enabled or disabled in the waypoint menu seems to be missing even though the function is still there and works.

![image](https://github.com/user-attachments/assets/353ae6a0-411a-427a-abe3-57dcf592b73b)

**Comment by fantahund** [comment]
Fixed in https://github.com/fantahund/VoxelMap/commit/11931e01a57ae227b52b4d3ca488ec58dabd9a9e The fix comes with the 1.21.4 release
