### ISSUE TITLE
Add `Zaneris` & `Lahwran` to mod's authors

### ISSUE THREAD

**Issue by NatoBoram** [fantahund/VoxelMap#8]
At this part:

https://github.com/fantahund/VoxelMap/blob/1172342a11ef0757cb98fccc21520daa143f7d31/src/main/resources/fabric.mod.json#L7-L10

I think it would be nice to honour the earlier version of VoxelMap, Zan's Minimap.

* https://github.com/MamiyaOtaru/voxelmap
* https://tekkify2.fandom.com/wiki/Zans_Minimap

**Comment by turikhay** [comment]
> The Zans Minimap was originally made by Zaneris (who stopped maintaining the mod) who handed the project to Lahwran. Later, Lahwran also stopped maintaining the mods that he made and handed the project to MamiyaOtaru. 

[[1]](https://tekkify2.fandom.com/wiki/Zans_Minimap)

**Comment by fantahund** [comment]
Done https://github.com/fantahund/VoxelMap/commit/a371bdce331dfe9a8d8814ac1f4324886ab2b5d0

**Comment by fantahund** [comment]
Done https://github.com/fantahund/VoxelMap/commit/a371bdce331dfe9a8d8814ac1f4324886ab2b5d0
